# Generated by Django 4.1.7 on 2023-03-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chekin', models.TimeField()),
                ('chekout', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
