# Generated by Django 4.1.7 on 2023-03-24 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontos',
            options={'verbose_name': 'Ponto'},
        ),
        migrations.AlterField(
            model_name='pontos',
            name='chekin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pontos',
            name='chekout',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pontos',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
