# Generated by Django 4.1.7 on 2023-03-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0004_remove_pontos_chekout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontos',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
