# Generated by Django 4.1.7 on 2023-03-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0005_alter_pontos_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontos',
            name='chekin',
            field=models.TimeField(auto_now=True),
        ),
    ]
